version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: lsa2-node
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    environment:
      - NODE_ENV=development
    networks:
      mynet:
        ipv4_address: 172.31.0.8
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: scott
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: camp
      TZ: Asia/Seoul
    ports:
      - "43432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./backup/data:/var/lib/postgresql/data
      # - ./backup/conf:/etc/postgresql
      # - ./backup/logs:/var/log/postgresql
      # - ./backup/lib:/usr/lib/postgresql
      # - ./backup:/docker-entrypoint-initdb.d
    networks:
      mynet:
        ipv4_address: 172.31.0.7

  tomcat:
    image: tomcat:9.0
    environment:
      TZ: Asia/Seoul
    ports:
      - "42888:8080"
      - "42022:22"
    volumes:
      - ./backup/webapps:/usr/local/tomcat/webapps
      - ./backup/conf:/usr/local/tomcat/conf
      - ./backup/logs:/usr/local/tomcat/logs
      - ./backup/lib:/usr/local/tomcat/lib
    networks:
      mynet:
        ipv4_address: 172.31.0.6

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
    name: lsa2_mynet
    ipam:
      config:
        - subnet: 172.31.0.0/16
